POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2NGI2ODQxNWNhYjRlYTRhZGE4OTRiMGUiLCJpYXQiOjE2ODk2ODI5ODF9.DiP8zrJPdDN_MyrrvPwzM97gJ3ppqfhOy6uSqKafqs0

{
    "title":"testi123",
    "author":"tester112223",
    "url":"www.aasddssdssaadd.aaaa.2",
    "likes":"8"
}